# Generated by Django 5.1.7 on 2025-04-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.FloatField(verbose_name='Коэффициент совпадения резюме с вакансией')),
                ('shortage', models.JSONField(verbose_name='Нехватка навыков')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first_name')),
                ('patronymic_name', models.CharField(max_length=150, verbose_name='patronymic_name')),
                ('surname', models.CharField(blank=True, max_length=150, null=True)),
                ('job', models.CharField(blank=True, max_length=156, null=True)),
                ('skills', models.JSONField(verbose_name='Перечень навыков')),
                ('resume_file', models.JSONField(verbose_name='Распарсенный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('required_skills', models.JSONField(verbose_name='Требуемые навыки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
