# Generated by Django 5.1.7 on 2025-04-17 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('required_skills', models.JSONField(verbose_name='Требуемые навыки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('job', models.CharField(blank=True, max_length=156, null=True)),
                ('skills', models.JSONField(blank=True, null=True, verbose_name='Перечень навыков')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('parsed_resume', models.TextField(verbose_name='Распаршенный файл')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Название файла')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='HR')),
            ],
        ),
        migrations.CreateModel(
            name='JobMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.FloatField(verbose_name='Коэффициент совпадения резюме с вакансией')),
                ('shortage', models.JSONField(verbose_name='Нехватка навыков')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('HR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.resume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.vacancy')),
            ],
        ),
    ]
