# Generated by Django 5.1.7 on 2025-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(blank=True, null=True, verbose_name='Перечень навыков'),
        ),
    ]
