# Generated by Django 5.1.7 on 2025-04-03 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatching',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobmatching',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.resume'),
        ),
        migrations.AddField(
            model_name='jobmatching',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.vacancy'),
        ),
    ]
