# Generated by Django 5.1.7 on 2025-04-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_alter_resume_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='patronymic_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='patronymic_name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='surname',
            field=models.CharField(max_length=150),
        ),
    ]
